[path]
anime = [
    "D:\\KOLEKSI\\ANIME_NEW",
]
exclude = ["1. new","2. IconGenerator", "$RECYCLE.BIN"]

[api]
query = """
        query ($search: String){ 
            Media(search: $search, type:ANIME) { 
                id 
                coverImage {
                    extraLarge
                }
            }
        }
        """
url = "https://graphql.anilist.co/"

[img]
bottom = "src\\img\\bottom.png"
top = "src\\img\\top.png"